apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configfile
data:
  prometheus.yml: |-
    global: 
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting: 
      alertmanagers:
      - static_configs: 
        - targets: 
    rule_files:
    scrape_configs:
      - job_name: 'rhelnode'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'clinode'
        static_configs:
        - targets: ['192.168.43.39:9100']
