apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
    dc: IN
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30001
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host1
  labels:
    app: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:"/var/lib/docker/volumes/shivam1/_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  labels:
    app: prometheus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom1
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
      dc: IN
  template:
    metadata:
      name: myweb1
      labels:
        app: prometheus
        dc: IN
    spec:
      containers:
      - name: myprom
        image: shivam3120/prometheus:v1
        volumeMounts:
        - name: prometheus-vol
          mountPath: /prometheus-2.19.2.linux-amd64/data
        - name: prometheus-configfile
          mountPath: /prometheus-2.19.2.linux-amd64/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-vol
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: prometheus-configfile
        configMap:
        name: prometheus-configfile
